id: ICC5EE327
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:38:19+00:00'
last_modified: '2022-06-08T04:55:20.981631+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016705
  title: སྲས་མཁར་དགུ་ཐོག་སོགས་བོད་ཀྱི་གནས་ཡིག་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ECAE:
      image_group_id: I01JW28
      title: ''
      total_pages: 402
      order: 1
      base_file: ECAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
