id: P005560
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:02:33.996456
source_metadata:
  id: bdr:W00EGS1016705
  title: སྲས་མཁར་དགུ་ཐོག་སོགས་བོད་ཀྱི་གནས་ཡིག་ཁག་ཅིག
  author: ''
  volumes:
    b77985275c544652bff7688560159b85:
      image_group_id: I01JW28
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
